var classes = [
    {
        "name": "Tina4\\HTMLElement",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "determineParamType",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getElements",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAttributes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 30,
        "ccn": 26,
        "ccnMethodMax": 9,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 179,
        "vocabulary": 38,
        "volume": 939.38,
        "difficulty": 25.67,
        "effort": 24110.73,
        "level": 0.04,
        "bugs": 0.31,
        "time": 1339,
        "intelligentContent": 36.6,
        "number_operators": 53,
        "number_operands": 126,
        "number_operators_unique": 11,
        "number_operands_unique": 27,
        "cloc": 42,
        "loc": 129,
        "lloc": 87,
        "mi": 72.04,
        "mIwoC": 33.38,
        "commentWeight": 38.66,
        "kanDefect": 2.07,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.85,
        "relativeSystemComplexity": 9.85,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 4.25,
        "totalSystemComplexity": 49.25,
        "package": "Tina4\r\\",
        "pageRank": 1,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "numberOfUnitTests": 1,
        "violations": {}
    }
]